### ISSUE TITLE
Hang when LB rule is added when loxilb docker is starting 

### ISSUE THREAD

**Issue by dj-nlx** [loxilb-io/loxilb#30]
This has been reported by @backguynn many times. Need to debug this

**Comment by backguynn** [comment]
If loxilb is turned off BGP mode, but user call REST API for LB creation with BGP options in the body, hang occurs.

This is because the AddBGPRule function in gobgpclient.go uses the GoBgpH(GoBGP handler) object's mutex.Lock.
GoBgpH is not initiated because BGP mode is off.
But AddBGPRule function is trying to get permission for the GoBgpH lock.

If GoBGP Handler is not created, the corresponding function must be not called.
