### ISSUE TITLE
SCTP Load Balancing on Kubernetes

### ISSUE THREAD

**Issue by souravpaul8** [loxilb-io/loxilb#683]
Can loxiLB redirect requests from an existing SCTP connection to a new replica if the original replica goes down? If yes, how does this redirection work? Can loxiLB do this without any change on the client side ? If yes then how ?

**Comment by TrekkieCoder** [comment]
Hi @souravpaul8 As of now loxilb can redirect request without any change in client side during LB node failover. But it can't simply redirect request to any new replica when original replica goes down because SCTP is connection/session oriented protocol after all. However if the endpoints are aware of which session the particular stream belongs to, based on cookies or some other mechanism, then it is possible to do so.

**Comment by UltraInstinct14** [comment]
We are finally here with [support](https://www.loxilb.io/post/ngap-load-balancing-with-loxilb) for stateful SCTP application. I hope you find it useful.
